### ISSUE TITLE
stream subjects overlap is not checked on stream edit/update

### ISSUE THREAD

**Issue by typecampo** [nats-io/nats-server#2144]
Streams are not allowed to listen to the same subjects as other streams. When trying to add a stream that listens to the same subjects of an existing stream the error `subjects overlap with an existing stream` is produced.

This check does not occur when editing a streams subject.

To reproduce:

Add a stream that listens to a subject.
Add a second stream that listens to a different subject.
Edit the second stream to listen to the same subject as the first stream.

This is confirmed to be the case using nats.go UpdateStream() as well ass the natscli nats stream edit.

**Comment by derekcollison** [comment]
Thanks, will get this fixed.

**Comment by robinsmidsrod** [comment]
Sorry for commenting on an old issue, but where in the documentation is *Streams are not allowed to listen to the same subjects as other streams* stated? I just can't find it anywhere.

**Comment by mt-rcampo** [comment]
It’s not in the docs because it was a bug. Should be fixed by now I assume.

**Comment by ripienaar** [comment]
Streams are still not allowed to overlap.

The reason for this is because when publishing to one fails but succeed to the other you cannot really recover from that situation, you cant publish to just the one that didnt get the message and if you did try to republish using the message id header for dedup the 2 streams could be out of order. We feel this doesnt really deliver what people want to achieve when they make overlapping streams and error situations users cannot recover from is not a good experience.

Better is to use a mirror/source to ingest data from your main stream and create a aggregate second stream.  Mirrors and sources are reliable and offer ordering guarantees, retries on failures etc.

With subject mapping in streams (2.10) you can alter the messages in flight to create new derived streams with different internal shapes.

**Comment by jnmoyne** [comment]
Notice the distinction: different streams can _contain_ messages with the same subject (e.g. one stream sources from the other) but different streams can not _listen_ to the same subjects.
