### ISSUE TITLE
Leaf nodes do not receive messages from remote nodes properly

### ISSUE THREAD

**Issue by LLLLimbo** [nats-io/nats-server#3009]
# Description
I started a NATS cluster with three remote nodes and one leaf node. They are configured as follows:
https://github.com/LLLLimbo/nats-conf/tree/main
At first they work fine, the leaf nodes receive the messages correctly when I publish them to the remote nodes and vice versa, but whenever they run for a while, it happens that the leaf nodes do not receive the messages from the remote nodes correctly.
![GIF](https://user-images.githubusercontent.com/31607003/161912213-818a312c-c111-4789-84e1-e4bf8e01be13.gif)

~~The problem may be related to jetstream, when I delete the storage file of jetstream, the cluster is back to normal.~~
2022-04-12 correction：A simple restart restores communication between the remote node and the leaf node.

*Environment*
- nats-version : 2.7.3
- system: centos 7.6

**Comment by derekcollison** [comment]
I suspect the authorization block for the servers receiving leafnode connections may be incorrect.

**Comment by LLLLimbo** [comment]
> I suspect the authorization block for the servers receiving leafnode connections may be incorrect.

I encountered this problem again, this time I tried to delete only the Jetstream storage on the leaf node and the cluster returned to normal.

**Comment by kozlovic** [comment]
@LLLLimbo Would you mind sending some reports from the NATS cli tools (`nats`) to see if you have some streams defined, how their configuration look like, etc? I believe you are using MQTT too, are you having MQTT applications subscribing to "test"? Usually, how long does it take before the failure start to occur? Any servers restart before it starts to fail?

**Comment by LLLLimbo** [comment]
> @LLLLimbo Would you mind sending some reports from the NATS cli tools (`nats`) to see if you have some streams defined, how their configuration look like, etc? I believe you are using MQTT too, are you having MQTT applications subscribing to "test"? Usually, how long does it take before the failure start to occur? Any servers restart before it starts to fail?

1. I didn't define any jetstream streams.
2. I don't have any  MQTT client subscribes to `test`
3. I can't give a specific time, but usually after a few hours
4. There is no reboot

The following information is obtained（from leafnode） when the cluster is working properly.
```
PS C:\DevelopmentKit\nats\nats-cli> ./nats --server nats://seeiner-edge:seeiner123@192.168.3.131:4222 account info
Connection Information:

               Client ID: 25
               Client IP: 192.168.9.251
                     RTT: 2.2613ms
       Headers Supported: true
         Maximum Payload: 1.0 MiB
       Connected Cluster: nats-edge
           Connected URL: nats://seeiner-edge:seeiner123@192.168.3.131:4222
       Connected Address: 192.168.3.131:4222
     Connected Server ID: NBSKY74RGOL5DQ32T77BU5J73GBL6MPGDDGUIJRYU54YQNABE2DMX6EE
   Connected Server Name: nats-edge

JetStream Account Information:

           Memory: 0 B of Unlimited
          Storage: 816 B of Unlimited
          Streams: 3 of Unlimited
        Consumers: 1 of Unlimited
```
```
PS C:\DevelopmentKit\nats\nats-cli> ./nats --server nats://seeiner-edge:seeiner123@192.168.3.131:4222 stream ls
No Streams defined, pass -a to include system streams
```

**Comment by kozlovic** [comment]
I am guessing that `nats stream ls -a` will list the 3 MQTT streams, and nothing more, right?

**Comment by LLLLimbo** [comment]
> 
There are indeed three MQTT streams
```
PS C:\DevelopmentKit\nats\nats-cli> ./nats --server nats://seeiner-edge:seeiner123@192.168.3.131:4222 stream ls -a
╭───────────────────────────────────────────────────────────────────────────────────╮
│                                      Streams                                      │
├─────────────┬─────────────┬─────────────────────┬──────────┬───────┬──────────────┤
│ Name        │ Description │ Created             │ Messages │ Size  │ Last Message │
├─────────────┼─────────────┼─────────────────────┼──────────┼───────┼──────────────┤
│ $MQTT_msgs  │             │ 2022-04-06 23:04:58 │ 0        │ 0 B   │ never        │
│ $MQTT_rmsgs │             │ 2022-04-06 23:04:58 │ 0        │ 0 B   │ never        │
│ $MQTT_sess  │             │ 2022-04-06 23:04:58 │ 4        │ 816 B │ 45m47s       │
╰─────────────┴─────────────┴─────────────────────┴──────────┴───────┴──────────────╯
```

**Comment by kozlovic** [comment]
What are the server versions? Have you tried with the latest from main or nightly build?

**Comment by LLLLimbo** [comment]
> What are the server versions? Have you tried with the latest from main or nightly build?

The version I am currently using is 2.7.3, but I had the same problem on 2.7.4.

**Comment by kozlovic** [comment]
You are normally using MQTT clients, but for the issue you are reporting, this is core NATS, subscribing on "test" (or any other subject). What made you try that? Did you notice communication issues that made you try the nats sub? In the screen capture, it seems like you are simply subscribing on "test", not on a queue, which I know we have fixed an issue related to queue group and leafnodes (https://github.com/nats-io/nats-server/pull/2901).

Anyway, thank you for all the details. Will try to reproduce but it may take time if, as you reported, it does not happen right away.

**Comment by LLLLimbo** [comment]
> 

In general, we only allow devices to connect to leaf nodes using MQTT. Ideally, our back-end application uses the NATS protocol to connect to a remote NATS node and then sends a message to the device, which receives it on the leaf node. Then we ran into the problem described in this issue, which we initially thought was related to MQTT, but I still ran into the problem after trying to connect to the leaf node using a NATS client.

**Comment by LLLLimbo** [comment]
I will also continue to try to find the trigger conditions for that issue.

**Comment by kozlovic** [comment]
@LLLLimbo I was not able to reproduce so far. What I would recommend is that you run with `-DV` (debug and trace) and make sure that your log are not limited (as they are now to 100MB) to make sure we capture the lack of interest propagation (if this is is what is happening). Thank you for your cooperation. (I will still continue to see if I can reproduce, but does not seem to be an obvious issue).

**Comment by LLLLimbo** [comment]
> @LLLLimbo I was not able to reproduce so far. What I would recommend is that you run with `-DV` (debug and trace) and make sure that your log are not limited (as they are now to 100MB) to make sure we capture the lack of interest propagation (if this is is what is happening). Thank you for your cooperation. (I will still continue to see if I can reproduce, but does not seem to be an obvious issue).

Thank you for your assistance! I will try to capture the relevant information in the logs. However, the problem hasn't happened since I last manually cleaned the jetstream storage on the leaf nodes and I need to keep waiting.

**Comment by LLLLimbo** [comment]
@kozlovic 
I have a log of the leaf node here, the first reboot occurred on 2022/04/07 07:02:54, the purpose of the reboot was to verify that deleting only the leaf node jetstream storage would bring communication back to normal. After this reboot, as of now there are no problems at the moment
[logs.zip](https://github.com/nats-io/nats-server/files/8447462/logs.zip)
.

**Comment by kozlovic** [comment]
@LLLLimbo I see the `SUB test 1` and the sent of interest, and then receiving the message. So as you say, here everything is working fine. If you can reproduce, I would need the logs of ALL servers, to see the interest propagation (or lack thereof) and the log from the server the publisher publishes to.
I understand that it may take some time to get it to fail and logs may become big, so if you have to recycle them (or keep the size limit) I understand, hopefully it will still cover whatever event that initiated the issue.

**Comment by LLLLimbo** [comment]
@kozlovic 
Here is the log of the remote node.   https://github.com/LLLLimbo/nats-conf/releases/tag/1.0
The remote node I have also performed a manual reboot, but the purpose of the reboot was to try to reproduce the issue.

**Comment by LLLLimbo** [comment]
`Delaying PING due to client activity` appears frequently in the logs of the leaf nodes, I wonder if this is the possible cause.

**Comment by kozlovic** [comment]
Any timeframe you could give me when you created the SUB on test on the "edge" server and that you then tried to send (from which server) and that message was not received?

**Comment by LLLLimbo** [comment]
> Any timeframe you could give me when you created the SUB on test on the "edge" server and that you then tried to send (from which server) and that message was not received?

This happens before I redeploy the whole cluster and I will try to reproduce and collect new logs for you.

**Comment by LLLLimbo** [comment]
@kozlovic 
I encountered the problem again, but this time it took two days.
You can see in log  131 that I subscribed to `downwards.device.msg.202204110827` on `2022-04-11 08:27:26`, and in log 134 that I publisha message to that subject on `2022-04-11 08:27:28`
https://github.com/LLLLimbo/nats-conf/releases/tag/2022-04-11

**Comment by LLLLimbo** [comment]
When I access the web monitor (http://192.168.3.131:8222/leafz) of 131 (i.e. the leaf node), it shows that the currently connected remote node is 136.

```json
{
  "server_id": "NB73QCEZBAJ4U2ASAMURWZICPZXXKTM456RJGCLJH46BL6HSRWAISQIU",
  "now": "2022-04-11T00:44:50.65748122Z",
  "leafnodes": 1,
  "leafs": [
    {
      "account": "SEEINER",
      "ip": "192.168.3.136",
      "port": 7422,
      "rtt": "1.65919ms",
      "in_msgs": 86,
      "out_msgs": 1244,
      "in_bytes": 14805,
      "out_bytes": 69153,
      "subscriptions": 58
    }
  ]
}```

**Comment by kozlovic** [comment]
@LLLLimbo I am sorry, but downloading log-136.zip shows that this is the log of nats-edge, which is 131. The 134 and 135 logs correctly display logs for nodes nats-test-node-1 and nats-test-node-2 respectively, but 136 logs seem of the wrong server.

**Comment by LLLLimbo** [comment]
> @LLLLimbo I am sorry, but downloading log-136.zip shows that this is the log of nats-edge, which is 131. The 134 and 135 logs correctly display logs for nodes nats-test-node-1 and nats-test-node-2 respectively, but 136 logs seem of the wrong server.

My fault, I have re-uploaded.

**Comment by kozlovic** [comment]
@LLLLimbo I believe that the issue has to do with a leafnode restarting or recreating a connection and should be addressed in PR that has just been merged. It should be available in the nightly today or in the release v2.8.0 that should be coming out very shortly.

**Comment by LLLLimbo** [comment]
> @LLLLimbo I believe that the issue has to do with a leafnode restarting or recreating a connection and should be addressed in PR that has just been merged. It should be available in the nightly today or in the release v2.8.0 that should be coming out very shortly.

@kozlovic 
After I updated to version 2.8.0, I still encountered this problem and I re-uploaded the log:
https://github.com/LLLLimbo/nats-logs/releases/tag/2022-04-20
You can see on the log 131： I subscribed to `downwards.device.msg.202204200812` on the leaf node on `2022/04/20 08:12:21`
On the log 136 : I sent a message to `downwards.device.msg.202204200812` on `2022/04/20 08:12:25`

**Comment by kozlovic** [comment]
@LLLLimbo I see that you did a config reload on 131 and auth users was reloaded. Could you describe what was changed? Is the repo https://github.com/LLLLimbo/nats-conf still a good place to see the previous config and you describe the change that was done? I could then try to reproduce and see if that is the reason for the issue.

**Comment by LLLLimbo** [comment]
@kozlovic I did not change the configuration

**Comment by kozlovic** [comment]
I saw that in the 131's logs:
```
[25892] 2022/04/19 20:28:07.588347 [DBG] Trapped "hangup" signal
[25892] 2022/04/19 20:28:07.592906 [INF] Reloaded: authorization users
[25892] 2022/04/19 20:28:07.593009 [INF] Reloaded: accounts
[25892] 2022/04/19 20:28:07.593192 [INF] Reloaded: cluster
```
Will see if a reload prints that without any change using your nats-conf repo. Thanks!

**Comment by kozlovic** [comment]
Yes, I have verified that this is printed even without configuration modification. I will investigate. Thank you for your patience.

**Comment by LLLLimbo** [comment]
I'm sure no changes have been made to the configuration file.
So you can continue to use the configuration in the nats-conf repo.

**Comment by LLLLimbo** [comment]
> Yes, I have verified that this is printed even without configuration modification. I will investigate. Thank you for your patience.

Thank you also for your continued interest in this issue! I will always cooperate if there is any need.

**Comment by kozlovic** [comment]
Well, that's embarrassing, I can easily reproduce with the config reload. I guess a v2.8.1 will be needed soon. As a workaround, you can restart the server that had a "reload" signal issued, and unlike the original issue, restarting the server will actually fix the interest propagation issue.

Again, thank you for your patience and sorry for all the troubles.

**Comment by LLLLimbo** [comment]
@kozlovic 
Thank you for your quick response !

**Comment by kozlovic** [comment]
Weird, the test case I created for the original issue, when modified to do a config reload, does not show the problem. So will need more time to investigate.

**Comment by kozlovic** [comment]
Final update for me today, I was actually able to reproduce. I had to modify the test to stop/restart the consumer too, not just the publisher.
