### ISSUE TITLE
RAFT: truncateWAL may be silently failing

### ISSUE THREAD

**Issue by caleblloyd** [nats-io/nats-server#3870]
Issue reported on `nats` 2.9.11 cluster, but I have referenced the code in `dev` for debugging here

Error message `Wrong index...` should result in truncateWAL but the message repeats millisecond(s) later with `seq` still increasing.

https://github.com/nats-io/nats-server/blob/9c02be2409d70b98734204bb2fbe121811ba4bf3/server/raft.go#L3117-L3129

It looks like this call to `truncateWAL` may be silently failing in this case.

Further down the logs, a Restart occurs followed by `Corrupt WAL, will truncate`, which does work because the `seq` in the next `Wrong index...` error has dropped from 21595855 to 21568766.

https://github.com/nats-io/nats-server/blob/9c02be2409d70b98734204bb2fbe121811ba4bf3/server/raft.go#L456-L462

Logs:

```
nats [269] 2023/02/14 10:55:22.765822 [WRN] RAFT [074XQSJo - S-R3F-Q3OExCBX] Wrong index, ae is &{leader:4zcZUjUn term:82 commit:21568649 pterm:82 pindex:21568649 entries: 1}, index stored was 21568700, n.pindex is 21568649
nats [269] 2023/02/14 10:55:22.765851 [WRN] RAFT [074XQSJo - S-R3F-Q3OExCBX] Error storing entry to WAL: raft: could not store entry to WAL
nats [269] 2023/02/14 10:55:22.765861 [WRN] RAFT [074XQSJo - S-R3F-Q3OExCBX] Expected first catchup entry to be a snapshot and peerstate, will retry
nats [269] 2023/02/14 10:55:22.768143 [WRN] RAFT [074XQSJo - S-R3F-Q3OExCBX] Wrong index, ae is &{leader:4zcZUjUn term:82 commit:21568649 pterm:82 pindex:21568649 entries: 1}, index stored was 21568701, n.pindex is 21568649
nats [269] 2023/02/14 10:55:22.769696 [WRN] RAFT [074XQSJo - S-R3F-Q3OExCBX] Wrong index, ae is &{leader:4zcZUjUn term:82 commit:21568649 pterm:82 pindex:21568649 entries: 1}, index stored was 21568702, n.pindex is 21568649
nats [269] 2023/02/14 10:55:22.771831 [WRN] RAFT [074XQSJo - S-R3F-Q3OExCBX] Wrong index, ae is &{leader:4zcZUjUn term:82 commit:21568649 pterm:82 pindex:21568649 entries: 1}, index stored was 21568703, n.pindex is 21568649
nats [269] 2023/02/14 10:55:22.774476 [WRN] RAFT [074XQSJo - S-R3F-Q3OExCBX] Wrong index, ae is &{leader:4zcZUjUn term:82 commit:21568649 pterm:82 pindex:21568649 entries: 1}, index stored was 21568704, n.pindex is 21568649
nats [269] 2023/02/14 10:55:22.776054 [WRN] RAFT [074XQSJo - S-R3F-Q3OExCBX] Wrong index, ae is &{leader:4zcZUjUn term:82 commit:21568649 pterm:82 pindex:21568649 entries: 1}, index stored was 21568705, n.pindex is 21568649
...more similar logs
nats [269] 2023/02/14 10:55:23.832975 [WRN] RAFT [074XQSJo - S-R3F-Q3OExCBX] Wrong index, ae is &{leader:4zcZUjUn term:82 commit:21568649 pterm:82 pindex:21568649 entries: 1}, index stored was 21568974, n.pindex is 21568649
nats [269] 2023/02/14 10:55:23.834738 [WRN] RAFT [074XQSJo - S-R3F-Q3OExCBX] Wrong index, ae is &{leader:4zcZUjUn term:82 commit:21568649 pterm:82 pindex:21568649 entries: 1}, index stored was 21568975, n.pindex is 21568649
nats [269] 2023/02/14 10:55:24.765639 [WRN] RAFT [074XQSJo - S-R3F-Q3OExCBX] Wrong index, ae is &{leader:4zcZUjUn term:82 commit:21568649 pterm:82 pindex:21568649 entries: 1}, index stored was 21568976, n.pindex is 21568649
nats [269] 2023/02/14 10:55:24.765665 [WRN] RAFT [074XQSJo - S-R3F-Q3OExCBX] Error storing entry to WAL: raft: could not store entry to WAL
nats [269] 2023/02/14 10:55:24.765674 [WRN] RAFT [074XQSJo - S-R3F-Q3OExCBX] Expected first catchup entry to be a snapshot and peerstate, will retry
nats [269] 2023/02/14 10:55:24.767578 [WRN] RAFT [074XQSJo - S-R3F-Q3OExCBX] Wrong index, ae is &{leader:4zcZUjUn term:82 commit:21568649 pterm:82 pindex:21568649 entries: 1}, index stored was 21568977, n.pindex is 21568649
nats [269] 2023/02/14 10:55:24.769311 [WRN] RAFT [074XQSJo - S-R3F-Q3OExCBX] Wrong index, ae is &{leader:4zcZUjUn term:82 commit:21568649 pterm:82 pindex:21568649 entries: 1}, index stored was 21568978, n.pindex is 21568649
nats [269] 2023/02/14 10:55:24.772130 [WRN] RAFT [074XQSJo - S-R3F-Q3OExCBX] Wrong index, ae is &{leader:4zcZUjUn term:82 commit:21568649 pterm:82 pindex:21568649 entries: 1}, index stored was 21568979, n.pindex is 21568649
...more similar logs
nats [269] 2023/02/14 10:57:53.910311 [WRN] RAFT [074XQSJo - S-R3F-Q3OExCBX] Wrong index, ae is &{leader:4zcZUjUn term:82 commit:21568700 pterm:82 pindex:21568700 entries: 1}, index stored was 21595853, n.pindex is 21568700
nats [269] 2023/02/14 10:57:53.911055 [WRN] RAFT [074XQSJo - S-R3F-Q3OExCBX] Wrong index, ae is &{leader:4zcZUjUn term:82 commit:21568700 pterm:82 pindex:21568700 entries: 1}, index stored was 21595854, n.pindex is 21568700
nats [269] 2023/02/14 10:57:53.911993 [WRN] RAFT [074XQSJo - S-R3F-Q3OExCBX] Wrong index, ae is &{leader:4zcZUjUn term:82 commit:21568700 pterm:82 pindex:21568700 entries: 1}, index stored was 21595855, n.pindex is 21568700
...RESTART
nats [303] 2023/02/14 11:01:15.636868 [WRN] RAFT [074XQSJo - S-R3F-Q3OExCBX] Corrupt WAL, will truncate
nats [303] 2023/02/14 11:01:15.763774 [WRN] RAFT [074XQSJo - S-R3F-Q3OExCBX] Wrong index, ae is &{leader:4zcZUjUn term:82 commit:21568764 pterm:82 pindex:21568764 entries: 1}, index stored was 21568766, n.pindex is 21568764
nats [303] 2023/02/14 11:01:15.763800 [WRN] RAFT [074XQSJo - S-R3F-Q3OExCBX] Error storing entry to WAL: raft: could not store entry to WAL
nats [303] 2023/02/14 11:01:15.763804 [WRN] RAFT [074XQSJo - S-R3F-Q3OExCBX] Expected first catchup entry to be a snapshot and peerstate, will retry
nats [303] 2023/02/14 11:01:15.765469 [WRN] RAFT [074XQSJo - S-R3F-Q3OExCBX] Wrong index, ae is &{leader:4zcZUjUn term:82 commit:21568764 pterm:82 pindex:21568764 entries: 1}, index stored was 21568767, n.pindex is 21568764
nats [303] 2023/02/14 11:01:15.767825 [WRN] RAFT [074XQSJo - S-R3F-Q3OExCBX] Wrong index, ae is &{leader:4zcZUjUn term:82 commit:21568764 pterm:82 pindex:21568764 entries: 1}, index stored was 21568768, n.pindex is 21568764
nats [303] 2023/02/14 11:01:15.770434 [WRN] RAFT [074XQSJo - S-R3F-Q3OExCBX] Wrong index, ae is &{leader:4zcZUjUn term:82 commit:21568764 pterm:82 pindex:21568764 entries: 1}, index stored was 21568769, n.pindex is 21568764
nats [303] 2023/02/14 11:01:15.772253 [WRN] RAFT [074XQSJo - S-R3F-Q3OExCBX] Wrong index, ae is &{leader:4zcZUjUn term:82 commit:21568764 pterm:82 pindex:21568764 entries: 1}, index stored was 21568770, n.pindex is 21568764
nats [303] 2023/02/14 11:01:15.773466 [WRN] RAFT [074XQSJo - S-R3F-Q3OExCBX] Wrong index, ae is &{leader:4zcZUjUn term:82 commit:21568764 pterm:82 pindex:21568764 entries: 1}, index stored was 21568771, n.pindex is 21568764
nats [303] 2023/02/14 11:01:15.774908 [WRN] RAFT [074XQSJo - S-R3F-Q3OExCBX] Wrong index, ae is &{leader:4zcZUjUn term:82 commit:21568764 pterm:82 pindex:21568764 entries: 1}, index stored was 21568772, n.pindex is 21568764
nats [303] 2023/02/14 11:01:15.776471 [WRN] RAFT [074XQSJo - S-R3F-Q3OExCBX] Wrong index, ae is &{leader:4zcZUjUn term:82 commit:21568764 pterm:82 pindex:21568764 entries: 1}, index stored was 21568773, n.pindex is 21568764
...more similar logs
```

**Comment by derekcollison** [comment]
I fixed this one..

**Comment by MauriceVanVeen** [comment]
The error message doesn't repeat as often in 2.9.14 (latest) any more. However, the wrong index, error storing, expected first catchup messages still happen in 2.9.14. For example, on creating a brand new cluster:
```
nats [7] 2023/02/15 08:20:04.901137 [INF] JetStream cluster new metadata leader: nats-1/nats                                                                                                                       
nats [7] 2023/02/15 08:20:04.902005 [WRN] RAFT [S1Nunr6R - _meta_] Wrong index, ae is &{leader:yrzKKRBu term:1 commit:2 pterm:1 pindex:2 entries: 1}, index stored was 2, n.pindex is 2                            
nats [7] 2023/02/15 08:20:04.902019 [WRN] RAFT [S1Nunr6R - _meta_] Error storing entry to WAL: raft: could not store entry to WAL                                                                                  
nats [7] 2023/02/15 08:20:04.902030 [WRN] RAFT [S1Nunr6R - _meta_] Expected first catchup entry to be a snapshot and peerstate, will retry    
```

On a cluster with 3 JetStream-enabled nodes. nats-1 became the leader, nats-0 logged these messages. These logs may also happen for streams on restart.

To reproduce:
```
kind create cluster
helm upgrade -i nats nats/nats --version 0.19.9 --set cluster.enabled=true --set nats.jetstream.enabled=true --set nats.jetstream.fileStorage.storageClassName=standard
```

**Comment by caleblloyd** [comment]
@MauriceVanVeen do those messages only appear once, and then go away? If so that would indicate that the truncate did work and it has self-healed. Or do they appear again further down the logs?

If they appear again for the same steam, is the "index written" higher or lower?

Also is there anything else you can share to help me reproduce? Are you constantly writing to a stream during the restart? Thanks

**Comment by MauriceVanVeen** [comment]
@caleblloyd they only appear once, and only on startup. Both for `_meta_` as for streams the index stored always equals the mentioned `n.pindex`, and it then restores.

The logs for `_meta_` trigger upon cleanly starting from scratch. So these already trigger it once for the `_meta_`:
```
kind create cluster
helm upgrade -i nats nats/nats --version 0.19.9 --set cluster.enabled=true --set nats.jetstream.enabled=true --set nats.jetstream.fileStorage.storageClassName=standard
```

As for the streams, indeed constant writing to the stream takes place, ~900mps for example.

(also, haven't seen these log messages prior to 2.9.11, I believe)

**Comment by caleblloyd** [comment]
I do not get that log message by default when installing a 3-node 2.9.14 nats cluster into k3s.  Are you running on a cloud provider - and if so can you share which one?

**Comment by caleblloyd** [comment]
@MauriceVanVeen I can recreate what you are seeing now by injecting some latency on the interfaces between containers in my k3s environemnt

**Comment by derekcollison** [comment]
Anything else specific to the test @caleblloyd ?

Wwe have ability to do latency between servers in our testing framework, what is the setup for JetStream? How many streams and how are they configured etc?

**Comment by MauriceVanVeen** [comment]
Included below are the stream configs for 6 streams:
- 2 interest-based
- 1 limits-based
- 3 KVs

All are R3 file-based streams, with R3 consumers as well, with varying message rates as noted below.

[kv1.txt](https://github.com/nats-io/nats-server/files/10753576/kv1.txt), <1mps, used by 1 application
[kv2.txt](https://github.com/nats-io/nats-server/files/10753577/kv2.txt), empty, not running currently
[kv3.txt](https://github.com/nats-io/nats-server/files/10753578/kv3.txt), ~1mps, used by 1 application
[stream1.txt](https://github.com/nats-io/nats-server/files/10753579/stream1.txt), ~600mps, 3 consumers
[stream2.txt](https://github.com/nats-io/nats-server/files/10753580/stream2.txt), ~900mps, 3 consumers
[stream3.txt](https://github.com/nats-io/nats-server/files/10753581/stream3.txt), ~30mps, 4 consumers


In terms of latency, the `nats rtt`:
```
nats://nats:

   nats://172.31.18.250:4222: 167.702µs
    nats://172.31.29.60:4222: 148.286µs
   nats://172.31.24.212:4222: 152.952µs
```

Deployed on AWS EKS, three NATS instances, one instance per node with instance type `c6i.xlarge`.

**Comment by caleblloyd** [comment]
I have been testing with different latency between servers of between 10ms - 50ms

100 R3 file streams writing at 100 messages/s of size 1KB with `nats bench`:

```
for i in $(seq 1 100); do
    echo "--- stream s$i"
    nats s create "s$i" --storage=file --replicas=3 --subjects="s$i.>" --retention=limits --discard=old --max-msgs=-1 --max-msg-size=-1 --max-msgs-per-subject=100 --max-bytes=-1 --dupe-window=2m --allow-rollup --deny-delete --no-deny-purge --max-age 0 >/dev/null
    nats bench --js --pub 1 --sub=1 --size=1024 --pull --consumerbatch=100 --storage=file --replicas=3 --msgs=120000 --pubsleep=10ms --purge --stream "s$i" "s$i" --multisubject --multisubjectmax=1000 --no-progress &
done
```

Then start a loop where I restart each server:

1. Stop Server
2. Sleep 2 minutes (simulate host maintenance, such as a restart)
3. Start Server
4. Wait for `/healthz` to report healthy
5. Move on to next server

Repeat that entire loop 10 times.  At the beginning of each restart, there are a bunch of these logs but they all resolve:

```
nats [7] 2023/02/14 16:36:07.690669 [WRN] RAFT [S1Nunr6R - C-R3F-XCvHwx7n] Wrong index, ae is &{leader:cnrtt3eg term:4 commit:5421161 pterm:4 pindex:5421162 entries: 1}, index stored was 5421162, n.pindex is 542
nats [7] 2023/02/14 16:36:07.690680 [WRN] RAFT [S1Nunr6R - C-R3F-XCvHwx7n] Error storing entry to WAL: raft: could not store entry to WAL                                                                          
nats [7] 2023/02/14 16:36:07.690684 [WRN] RAFT [S1Nunr6R - C-R3F-XCvHwx7n] Expected first catchup entry to be a snapshot and peerstate, will retry 
```

With higher latencies of around ~10ms+ the RAFT layer cannot seem to catch-up while under the sustained load, but if I stop all of the traffic it seems to eventually even out.

**Comment by derekcollison** [comment]
These have been addressed now. Will be included in 2.9.16 release tomorrow.
