### ISSUE TITLE
JetStream is discarding messages it likely shouldn't

### ISSUE THREAD

**Issue by aksdb** [nats-io/nats-server#5638]
### Observed behavior

We have a work queue stream that is being consumed by about 250 pull consumers and which requires ACKs. Recently (past weeks) we noticed, that a small fraction of messages get lost. Watching the ADVISORY subjects, it seems like JetStream drops the messages itself. Example:

```
13:20:39 {"type":"io.nats.jetstream.advisory.v1.terminated","id":"8pZH7RdhGdWrEJbkdfdy2D","timestamp":"2024-07-09T13:20:39.504816844Z","stream":"corejobs","consumer":"posts-PostSaved-worker","consumer_seq":311629,"stream_seq":49245214,"deliveries":1,"reason":"Unacknowledged message was deleted"}
```

The stream doesn't have a `MaxDeliver` set, and as you can see, it was just delivered once. So there should be no reason to drop it if an ACK was still pending. (We also saw messages being dropped with that reason that had `deliveries:0`.) From what I can tell, also limits were not exceeded - since the work queue only has very small messages (basically just headers without payload), the stream limit of 500 MB was certainly not reached. The message in question was also far younger than the maximum age (which is 7d; the message was barely a few minutes old).

Even more suspicious: our workers log processing of messages and we were not seeing this message ever hitting our worker. Also we sniffed the $JS-API and the _INBOX, and from what we can tell, the messages in question also never were delivered. We basically only see them being ACK'ed by JetStream as being received and soon after we see them being terminated in the advisory subject.

Here is the stream config of the stream in question:
```
Information for Stream corejobs created 2022-07-22 08:16:16

              Subjects: core.jobs.>
              Replicas: 3
              Storage: File

Options:

             Retention: WorkQueue
       Acknowledgments: true
        Discard Policy: Old
      Duplicate Window: 2m0s
     Allows Msg Delete: true
          Allows Purge: true
        Allows Rollups: false

Limits:

      Maximum Messages: unlimited
   Maximum Per Subject: unlimited
         Maximum Bytes: 500 MiB
           Maximum Age: 7d0h0m0s
  Maximum Message Size: unlimited
     Maximum Consumers: unlimited

Cluster Information:

                  Name: nats
                Leader: nats-cluster-4_v1
               Replica: nats-cluster-0_v1, current, seen 1.85s ago
               Replica: nats-cluster-3_v1, current, seen 1.85s ago

State:

              Messages: 0
                 Bytes: 0 B
        First Sequence: 420,487,665
         Last Sequence: 420,487,664 @ 2024-07-10 10:10:49 UTC
      Active Consumers: 238
```

Just in case, this is how our pull consumers look like:
```
Information for Consumer corejobs > notifications-SendMail-worker created 2024-02-06T09:58:48Z

Configuration:

                    Name: notifications-SendMail-worker
               Pull Mode: true
          Filter Subject: core.jobs.notifications.SendMail
          Deliver Policy: All
              Ack Policy: Explicit
                Ack Wait: 1m0s
           Replay Policy: Instant
         Max Ack Pending: 1,000
       Max Waiting Pulls: 512

Cluster Information:

                    Name: nats
                  Leader: nats-cluster-4_v1
                 Replica: nats-cluster-0_v1, current, seen 829ms ago
                 Replica: nats-cluster-3_v1, current, seen 829ms ago

State:

  Last Delivered Message: Consumer sequence: 3,652,619 Stream sequence: 420,486,612 Last delivery: 2m58s ago
    Acknowledgment Floor: Consumer sequence: 3,652,619 Stream sequence: 420,487,750 Last Ack: 2m58s ago
        Outstanding Acks: 0 out of maximum 1,000
    Redelivered Messages: 0
```

### Expected behavior

The messages should not be dropped.

### Server and client version

Server: 2.10.16 and 2.10.17
Client: Java SDK 2.19.1

### Host environment

Kubernetes on Azure

**Comment by kozlovic** [comment]
@aksdb I would recommend that you try with a build from main since I believe the fix in #5639 will address your issue. Once you confirm, we can close this issue.

**Comment by aksdb** [comment]
We'll deploy the latest nightly build and see how it behaves. I'll report back ASAP.

**Comment by chrisdelachal** [comment]
Hi all.
We encounter the same issue, event with the Release v2.10.18-RC.2.
in our case, we have an stream S1 on mytopic.>
we have 20 consumers C1 on mytopic.C1, C2 on mytopic.C2 , ..., C20 on mytopic.C20
each consumer from C1 to C19 publish data on mytopic.C20.
When consumer C20, fetch data from mytopic.C20 and ack a message, all other consumer loose their data.

**Comment by wallyqs** [comment]
@chrisdelachal can you share the `consumer info` from a couple of those consumers along with the `stream info`?

**Comment by chrisdelachal** [comment]
![Screenshot 2024-07-11 at 15 14 27-1](https://github.com/nats-io/nats-server/assets/46417617/ff2601b5-8092-4006-9d18-9f786bbad349)
![Screenshot 2024-07-11 at 15 13 54-2](https://github.com/nats-io/nats-server/assets/46417617/e1e62548-0c89-44f3-b776-1035359de332)
![Screenshot 2024-07-11 at 15 13 16-3](https://github.com/nats-io/nats-server/assets/46417617/f8d390ca-4c4b-450b-a41d-bb8ad1dc8b95)

**Comment by aksdb** [comment]
Two awesome colleagues of mine monitored the situation today. So as it seems, the behavior has changed a little bit with `synadia/nats-server:nightly-20240711`, but the problem persists.

We still saw messages being `TERM`ed with `deliveries:0`, however we actually saw that those message had been delivered, but were `NAK`ed by our worker (this can happen when the load is too high on a single worker and it wants to "send back" the message to be processed by someone else). As seen in our stream and consumer settings in the initial post, this should of course not lead to the messages being dropped.

It also _looks_ like this happens suspiciously often when pull consumers hit their pull timeout (at least the timestamps seemed to indicate that the `TERM`s happen around the same second of a minute, which seems to correlate with the second of the start of the service and therefore the initial pull).

**Comment by chrisdelachal** [comment]
FIY, if it can help you, as it was a major issue for us in production, we have downgraded to release 2.10.9 and hopefully the issue is temporary fixed.

**Comment by aksdb** [comment]
> FIY, if it can help you, as it was a major issue for us in production, we have downgraded to release 2.10.9 and hopefully the issue is temporary fixed.

Thanks :) Thankfully the only work queue we have (at the moment) is backed by another database (don't ask, please :roll_eyes: ) so we can mitigate by having a cron job re-schedule suspiciously old work items again every few minutes.

**Comment by kozlovic** [comment]
@aksdb I have not been able to reproduce the issue based on what you described. However, I found an opened issue that sounds quite similar (notion of Nak and timeout): https://github.com/nats-io/nats-server/issues/5526.
Out of curiosity, are you using the simplified JetStream API in the client (use of CreateOrUpdateXXX) or the "old" API?

**Comment by plucked** [comment]
I have the same or similar issue. I also tried the latest RC3 candidate.

In essence, 1 stream, many consumers with non wildcard subjects. When I push messages at a rate of about 10k, I see dropped messages. I tried several configurations: file vs memory, single replica vs 3 replicas, but non changed the outcome.

The machine is a google n2 one and I see about 500-700micro cores, so it's busy but not exhausted. I can not repro this myself on my Mac, only within kubernetes.

**Comment by kozlovic** [comment]
@plucked But are we sure in your case that there is no limit in max number of redeliveries? Because even if a message is not explicitly ack'ed, it if reaches the max number of redeliveries it will get removed. As for providing information to help reproduce: you mentioned that you are not able to reproduce on your Mac, but do you have a test case (some code) that simulate what you are doing? This could help us figure out the chain of events and either be lucky in reproducing or at least check code paths and see if we find something.
Because I continued trying to reproduce with Nak, purging the stream while some messages were pending, publishing new ones, updating the stream and/or consumer, etc.. and I am still not able to reproduce the issue. That is, so far messages are removed only when ack'ed or the stream is purged.

**Comment by plucked** [comment]
Update from my side, version 2.10.18 fixes it for us. I do not see any messages dropped anymore under load. I something comes up, I will create a ticket or update here if it is not closed.

**Comment by ThalesValentim** [comment]
Hi everyone,

We have been following this issue as the symptom of the issue is very similar compared to the issue we are facing on our JetStream work queue.
Unfortunately, version 2.10.18 didn't fix it for us and it wasn't possible to simulate it on a local environment (MacOS), even with Docker. 
Currently, it is only reproducible in a production environment.

We downgraded to version **2.10.14**, which the issue doesn't occur. It might give ideas of what could have been changed since then.

### Server and client version
Server: 2.10.16, 2.10.17 and 2.10.18
Client: NATS.js 2.28.0

### Host environment
Clustered NATS / 3 replicas
Docker
AWS

### Steps to reproduce
Our use case is straightforward. The message processing is very light. Each message processing generates a log entry. We expect the same amount of logged items as the amount of published messages as well:

1. Publish 1000+ messages to a single topic at once
2. At least 3 consumers subscribe to receive them
3. Messages are dropped without being acknowledged
4. Total log entries don't match the published messages

The queue settings are the following:
- ACK policy is Explicit 
- Manual ack is enabled
- Max ACK pending is 30
- Consumers have the same delivery group
- Discard policy is New

### We brought graphs that show the behavior of each NATS server version, 2.10.14 vs 2.10.18

[2.10.14] The following picture represents the expected behavior, where 1000 messages were pending in the work queue and consumed completely after about 4 minutes:
![Screenshot 2024-07-22 at 10 39 36](https://github.com/user-attachments/assets/3c369112-911c-45ce-85b9-c1a05d5d0588)

[2.10.18] The following shows pending messages being dropped right after publishing them. About 70-80% of the messages were not acknowledged. 
![Screenshot 2024-07-22 at 10 46 42](https://github.com/user-attachments/assets/16978ae3-ee7e-4b75-8f16-02d8281187be)

Would be there any other information we could provide to help investigate the issue?

**Comment by aksdb** [comment]
For us it's also still happening. We ran 2.10.18 for a few days and still saw terminated messages on our stream:
```
{"type":"io.nats.jetstream.advisory.v1.terminated","id":"a5wvC7ppU0tFv6oeAttEPh","timestamp":"2024-07-23T07:49:13.535409202Z","stream":"corejobs","consumer":"media-UpdateEntityReferences-worker","consumer_seq":1227973,"stream_seq":49364147,"deliveries":0,"reason":"Unacknowledged message was deleted"}
```

**Comment by ripienaar** [comment]
This one means the limit (max age, size etc) was hit for a message that was not yet processed by your app so I believe this is different.

**Comment by aksdb** [comment]
@ripienaar as you can see in the stream info posted in the bug report, the stream doesn't have a retry limit. The message is far younger than the 7d limit (only a few minutes) and the size of the stream is not exceeded either. There is no reason for JetStream to discard the message.

**Comment by kozlovic** [comment]
@aksdb @ripienaar @neilalexander I wonder then if this could be related with the opened PR: https://github.com/nats-io/nats-server/pull/5697?

**Comment by srs-adamr** [comment]
This exact issue is happening to us as well! 
.NET V2 SDK
nats:alpine:latest
3 node cluster
using MEMORY storage

**Comment by neilalexander** [comment]
Yes this should be fixed by #5697 in the next version.

**Comment by srs-adamr** [comment]
Now running version 2.10.18, gave it a test, this is still occuring.

![image](https://github.com/user-attachments/assets/abf67d02-b2e5-4113-8f02-9779af198602)

**Comment by derekcollison** [comment]
You would want to try nightly build from main which has the fix. This will be pulled into a 2.10.19 as well.

**Comment by derekcollison** [comment]
https://hub.docker.com/r/synadia/nats-server/tags

**Comment by aksdb** [comment]
The first impression with the nightly is good. At least we didn't see a `TERM` advisory yet. We will have to monitor it a bit more next week, since we can't directly trigger the behavior, so it may be we were just "lucky" today.

**Comment by srs-adamr** [comment]
We have seen the issue cease on the nightly! However, not sure if it's related, but our Deleted count on our Stream continues to rise, then randomly reset, however the stream messages aren't being cleared anymore! (We aren't deleting any messages that I'm aware of)

**Comment by aksdb** [comment]
So after a week of monitoring, it seems the initial problem is gone with the nightly build. We didn't get any unexpected `TERM`s anymore and apparently we also don't miss any messages.

**Comment by wallyqs** [comment]
Fixed via #5697 which is part v2.10.19
